config/routes.rb
Rails.application.routes.draw do

  root 'tweets#index'

  devise_for :users, :controllers => { registrations: 'registrations', 
  																		 :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, only: [:show, :index] do
    resources :tweets, except: [:index]
  end

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :tweets
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
				 
	devise :omniauthable, :omniauth_providers => [:twitter]

	def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
			user.email = "#{auth.info.nickname}@twitter.com"
			user.password = Devise.friendly_token[0,20]
			user.username = auth.info.nickname #assuming the user model has a name
		end
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:username, :email, :password,
																 :password_confirmation)
	end

	def account_update_params
		params.require(:user).permit(:username, :email, :password,
																 :password_confirmation, :current_password)
	end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_user, except: [:index]
	before_action :set_tweet, only: [:edit, :update, :destroy, :show]

  def index
    @tweets = Tweet.all.order("created_at desc")
  end

  def show
  end

  def new
   if is_authorized?
    @tweet = @user.tweets.new  
   else
    flash[:notice] = "Nice try.  You can't create tweets for other users."
    redirect_to user_path(@user)    
   end

  end

  def edit
    unless is_authorized?
      flash[:notice] = "Nice try.  You can't edit tweets for other users."
      redirect_to user_path(@user)
    end
  end	

  def create
  	@tweet = @user.tweets.build(tweet_params)

    if is_authorized?
  	 if @tweet.save
  		  redirect_to user_path(@user)
  	 else
  		  render :new
  	 end
    else
      flash[:notice] = "Nice try.  You can't create tweets for other users."
      render :new
    end  
  end


  def update
  	if is_authorized?
     if @tweet.update(tweet_params)
  		redirect_to user_path(@user)
  	 else
  		render :edit
  	 end
    end
  end

  def destroy
    if is_authorized?    
  	 @tweet.destroy
  	 redirect_to user_path(@user) 
    else
      flash[:notice] = "Nice try.  You can't delete tweets for other users."
      redirect_to user_path(@user)     
    end
  end

  private

    def is_authorized?
      @user == current_user
    end
      
    def set_user
      @user = User.find(params[:user_id])
    end

  	def set_tweet
  		@tweet = Tweet.find(params[:id])
  	end

  	def tweet_params
  		params.require(:tweet).permit(:body, :user_id)
  	end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

 def twitter
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    logger.info @user.inspect
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container page-top">
    <%= link_to "TwitterClone", root_path, class: "navbar-brand" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home", root_path, class: "nav-text" %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Profile", user_path(current_user), class: "nav-text" %></li>
          <li><%= link_to "Users", users_path, class: "nav-text" %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-text" %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "nav-text" %></li>
          <li><%= link_to "Log In", new_user_session_path, class: "nav-text" %></li>
        <% end %>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>TwitterClone</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/navbar' %>
		<div class="container">
			<p class="notice"><%= notice %></p>
			<p class="alert"><%= alert %></p>
			<%= yield %>
		</div>
	</body>
</html>

app/views/tweets/edit.html.erb
<h1> Edit Tweet </h1>
<%= form_for [@user, @tweet] do |f| %>

	<%= f.text_field :body %>

	<%= f.submit %>
<% end %>

app/views/tweets/index.html.erb
<h2>All Tweets</h2>

<div class="tweet-table">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Tweet</th>
				<th>User</th>
				<th>Link</th>
			</tr>
		</thead>
		<tbody class="table-list">   
			<% @tweets.each do |tweet|%>
				<tr>
					<td class="col-md-8"><%= tweet.body %></td>
					<td class="col-md-2"><%= link_to tweet.user.username, user_path(tweet.user) %></td>
					<td class="col-md-2"><%= button_to 'View Tweet', user_tweet_path(tweet.user, tweet), method: :get %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/tweets/new.html.erb
<h1> New Tweet </h1>
<%= form_for [@user, @tweet] do |f| %>

	<%= f.text_field :body %><br>

	<%= f.submit %>
<% end %>

app/views/tweets/show.html.erb
<h1>Tweet by <%= @tweet.user.username %></h1>
<br>
<h2><%= @tweet.body %></h2>
<br>
<%= button_to 'Back', root_path, method: :get %>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
	<% @users.each do |user| %>
		<li><%= user.username %></li>
		<li><%= user.email %></li>
	<% end %>
</ul>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<p>Stuff and things about you!</p>

<% if @user == current_user %>
	<%= button_to 'New Tweet', new_user_tweet_path(@user), method: :get %>
<% end %>

<h2>Tweets</h2>
<div class="tweet-table">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Tweet</th>
				<th>Link</th>
				<% if @user == current_user %>
					<th>Edit</th>
				<% end %>
			</tr>
		</thead>
		<tbody class="table-list">   
			<% @user.tweets.each do |tweet|%>
				<tr>
					<td class="col-md-8"><%= tweet.body %></td>
					<td class="col-md-2"><%= button_to 'View Tweet', user_tweet_path(tweet.user, tweet) %></td>
					<% if @user == current_user %>
						<td class="col-md-1"><%= button_to 'Edit', edit_user_tweet_path(tweet.user, tweet), method: :get %></td>
						<td class="col-md-1"><%= button_to 'Delete', user_tweet_path(tweet.user, tweet), method: :delete %></td>
					<% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>